---
CHANGE_START_POSITION: "true"
SAGEMAKER_SHARED_S3_PREFIX: "data-bf2623f9-3113-4f98-98e7-f406ae1ec22c/models/e480b373-8b2b-468d-9d96-946b87dc4fc2/sagemaker-robomaker-artifacts"
METRICS_S3_OBJECT_KEY: "data-bf2623f9-3113-4f98-98e7-f406ae1ec22c/models/e480b373-8b2b-468d-9d96-946b87dc4fc2/metrics/training/training-20211101013548-Fu4TLiXATnquzNsMWmfX_w.json"
AWS_REGION: "us-east-1"
NUMBER_OF_EPISODES: "0"
KINESIS_VIDEO_STREAM_NAME: "dr-kvs-372026249783-20211101013548-1bb141ad-eb44-428a-af27-1f1f61540722"
TRAINING_JOB_ARN: "arn:aws:deepracer:us-east-1:311333576795:training_job/Fu4TLiXATnquzNsMWmfX_w"
REWARD_FILE_S3_KEY: "data-bf2623f9-3113-4f98-98e7-f406ae1ec22c/models/e480b373-8b2b-468d-9d96-946b87dc4fc2/reward_function.py"
S3_KMS_CMK_ARN: "arn:aws:kms:us-east-1:372026249783:key/85febbbd-eabb-4c9e-b761-c4f5131f384a"
METRIC_NAMESPACE: "AWSDeepRacer"
ALTERNATE_DRIVING_DIRECTION: "false"
MP4_S3_OBJECT_PREFIX: "data-bf2623f9-3113-4f98-98e7-f406ae1ec22c/models/e480b373-8b2b-468d-9d96-946b87dc4fc2/videos/training/training-20211101013548-Fu4TLiXATnquzNsMWmfX_w"
ROBOMAKER_SIMULATION_JOB_ACCOUNT_ID: "372026249783"
WORLD_NAME: "AmericasGeneratedInclStart"
SIMTRACE_S3_BUCKET: "aws-deepracer-data-us-east-1-1"
METRICS_S3_BUCKET: "aws-deepracer-data-us-east-1-1"
MP4_S3_BUCKET: "aws-deepracer-data-us-east-1-1"
SIMTRACE_S3_PREFIX: "data-bf2623f9-3113-4f98-98e7-f406ae1ec22c/models/e480b373-8b2b-468d-9d96-946b87dc4fc2/sim-trace/training"
SAGEMAKER_SHARED_S3_BUCKET: "aws-deepracer-data-us-east-1-1"
RACE_TYPE: "TIME_TRIAL"
JOB_TYPE: "TRAINING"
MODEL_METADATA_FILE_S3_KEY: "data-bf2623f9-3113-4f98-98e7-f406ae1ec22c/models/e480b373-8b2b-468d-9d96-946b87dc4fc2/model_metadata.json"
METRIC_NAME: "TrainingRewardScore"
TARGET_REWARD_SCORE: "None"
